#!/bin/sh

# PROVIDE: pms

. /etc/rc.subr

name="pms"
rcvar=`set_rcvar`
start_cmd="${name}_start"
stop_cmd="${name}_stop"

load_rc_config $name

pms_start()
{
    if checkyesno "${rcvar}"; then
      echo "Starting PlexMediaServer"
      su root -c 'cd /usr/local/pms && ./start.sh'
    fi
}
pms_stop()
{
    if checkyesno "${rcvar}"; then
    echo "Stopping PlexMediaServer"
      su root -c 'pkill -9 "Plex*"'
    fi
}

run_rc_command "$1"